export const products = [
  {
    id: 1,
    name: "Gaming Laptop RTX 4070",
    price: 180000,
    originalPrice: 200000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Laptops",
    rating: 4.8,
    reviews: 124,
    inStock: true,
    description: "High-performance gaming laptop with RTX 4070 graphics card, perfect for gaming and content creation.",
  },
  {
    id: 2,
    name: "Mechanical Gaming Keyboard",
    price: 15000,
    originalPrice: 18000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Peripherals",
    rating: 4.6,
    reviews: 89,
    inStock: true,
    description: "RGB mechanical keyboard with Cherry MX switches for the ultimate gaming experience.",
  },
  {
    id: 3,
    name: "Adobe Creative Suite",
    price: 25000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Software",
    rating: 4.9,
    reviews: 256,
    inStock: true,
    description: "Complete creative software package including Photoshop, Illustrator, and Premiere Pro.",
  },
  {
    id: 4,
    name: "4K Gaming Monitor",
    price: 85000,
    originalPrice: 95000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Peripherals",
    rating: 4.7,
    reviews: 167,
    inStock: true,
    description: "27-inch 4K gaming monitor with 144Hz refresh rate and HDR support.",
  },
  {
    id: 5,
    name: "Gaming Desktop PC",
    price: 250000,
    originalPrice: 280000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Desktops",
    rating: 4.9,
    reviews: 203,
    inStock: true,
    description: "Pre-built gaming desktop with RTX 4080, Intel i7, and 32GB RAM.",
  },
  {
    id: 6,
    name: "Wireless Gaming Mouse",
    price: 8000,
    originalPrice: 10000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Peripherals",
    rating: 4.5,
    reviews: 145,
    inStock: true,
    description: "High-precision wireless gaming mouse with customizable RGB lighting.",
  },
  {
    id: 7,
    name: "SSD 1TB NVMe",
    price: 12000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Components",
    rating: 4.8,
    reviews: 312,
    inStock: true,
    description: "Ultra-fast NVMe SSD with 1TB capacity for lightning-fast boot times.",
  },
  {
    id: 8,
    name: "Gaming Headset",
    price: 18000,
    originalPrice: 22000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Peripherals",
    rating: 4.6,
    reviews: 198,
    inStock: true,
    description: "7.1 surround sound gaming headset with noise-canceling microphone.",
  },
  {
    id: 9,
    name: "Graphics Card RTX 4060",
    price: 95000,
    originalPrice: 110000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Components",
    rating: 4.7,
    reviews: 267,
    inStock: true,
    description: "NVIDIA RTX 4060 graphics card with 8GB VRAM for 1440p gaming.",
  },
  {
    id: 10,
    name: "Office Software Suite",
    price: 15000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Software",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    description: "Complete office productivity suite with word processing, spreadsheets, and presentations.",
  },
  {
    id: 11,
    name: "Gaming Chair",
    price: 35000,
    originalPrice: 40000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Gaming",
    rating: 4.5,
    reviews: 156,
    inStock: true,
    description: "Ergonomic gaming chair with lumbar support and adjustable armrests.",
  },
  {
    id: 12,
    name: "Webcam 4K",
    price: 12000,
    image: "/placeholder.svg?height=300&width=300",
    category: "Hardware",
    subcategory: "Peripherals",
    rating: 4.3,
    reviews: 78,
    inStock: true,
    description: "4K webcam with auto-focus and built-in microphone for streaming and video calls.",
  },
]
